### ISSUE TITLE
Keep best version of each resolution ?

### ISSUE THREAD

**Issue by snickers2k** [l3uddz/plex_dupefinder#19]
Hey.
Nice work. But is it possible to keep the best quality for each resolution ? e.g. keep best Version of 4k, 1080p aswell as 720p, but delete everything else ? To keep Plex Transcodes as low as possible, of course.

thanks

**Comment by desimaniac** [comment]
It has built in support for that. Just needs the resolutions defined in the config. Ill create a readme page for this project. But till then, take a look at an example config file here: https://github.com/Cloudbox/Cloudbox/wiki/Extras:-Plex-Dupefinder#example

**Comment by snickers2k** [comment]
thanks. but i still not understand how to do that exactly :/

**Comment by desimaniac** [comment]
`VIDEO_RESOLUTION_SCORES` will give more weight to higher resolutions. So with default settings, 4k will beat 1080p, etc.

**Comment by snickers2k** [comment]
yeah right. for 1080p and 720p makes no big difference. But 1080p and 4K is most likely 4 times the size of 1080p ... 
so my goal is to have 1080p and 4K Versions of the same Movie (especially to lower CloudDrive-Access).

**Comment by saltydk** [comment]
Outside of the scope of the project.
