### ISSUE TITLE
Duplicates identified but doesn't start the interactive interface to delete

### ISSUE THREAD

**Issue by andrecastillo** [l3uddz/plex_dupefinder#33]
When I run plex_dupefinder, it'll show x duplicates identified in Movies library, but the interactive mdoe doesn't start, just drops out to my command line. No errors.

After a fresh install, following the readme, just run plex_dupefinder. 

Ubuntu 19.10

**Comment by charlestephen** [comment]
Same

**Comment by jorjenava** [comment]
I'm experiencing the same issue on ubuntu 19.10 both interactive and automatic modes are doing the same thing.

**Comment by impressiver** [comment]
Check the `activity.log`. I had an error at the end of the logs because I don't have a libary called `TV` which is included in the default `config.json`. Make sure your libraries in the config match what you have on the server.

**Comment by JacobRReed** [comment]
Ya this can be closed I think, If you change your "TV" to whatever your library name is (probably "TV Shows"), it should work

**Comment by aldodelgado** [comment]
I agree with @JacobRReed, this can be closed. If you look at https://github.com/l3uddz/plex_dupefinder/blob/master/config.py#L62 you will see where the Library "TV" is listed. You'll also find it in your `config.json`. Just change this to what you use "TV Shows" by default and it should work.
