### ISSUE TITLE
README

### ISSUE THREAD

**Issue by zimmertr** [l3uddz/plex_dupefinder#6]
Hey dude, could you please post a quick README sometime on how to use this? I'm really interested in using this project but I'm unsure how to get started.

**Comment by dskvr** [comment]
Readme would still be helpful.

**Comment by majorgiant** [comment]
- git clone https://github.com/l3uddz/plex_dupefinder.git
- pip3 install -r requirements.txt
- python3 config.py
- nano config.json (add your server and api and change any other stuff to your likings)
- python3 plexdupes.py to clean up your duplicate files


you can change the config to autodelete and then plexdupes to a crontab if you want to run the script automaticly ever x hours/days/weeks.

**Comment by desimaniac** [comment]
Readme created.
