### ISSUE TITLE
[Feature Request] Add ability to obtain token by authenticating with Plex.

### ISSUE THREAD

**Issue by rigrassm** [l3uddz/plex_dupefinder#7]
It would be nice to be able to set the Plex token by authenticating directly with Plex.

I have added this feature to my fork of this repo and wanted to see if you would consider a pull request if I were to make one?

**Comment by rigrassm** [comment]
Sounds good, opened pull request #9 for you to consider.

**Comment by desimaniac** [comment]
Added in a9535941b79d825cfdff078ac28088603b652c7a
